FROM node:22-alpine

WORKDIR /app

COPY package*.json ./

RUN npm install --no-cache
RUN npm install -D @swc/cli @swc/core

COPY . .

ENV NEXT_TELEMETRY_DISABLED=1
ENV NODE_ENV=development
ENV PORT=3035

EXPOSE 3035

CMD ["npm", "run", "dev"]
