services:
  nextjs:
    build:
      dockerfile: Dockerfile.prod
    env_file: .env
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.next-client.rule=Host(`diegoenriquezserrano.com`)"
      - "traefik.http.routers.next-client.entrypoints=websecure"
      - "traefik.http.routers.next-client.tls.certResolver=letsencrypt"
      - "traefik.http.services.next-client.loadbalancer.server.port=3035"
    networks:
      - dokploy-network
    ports:
      - 3035
    restart: on-failure
    volumes:
      - nextjs_cache:/app/.next
      - .:/app
volumes:
  nextjs_cache:
networks:
  dokploy-network:
    external: true