services:
  nextjs:
    build:
      dockerfile: Dockerfile.dev
    env_file: .env.docker
    networks:
      - diegoenriquezserrano_net
    ports:
      - "3035:3035"
    restart: on-failure
    volumes:
      - nextjs_cache:/app/.next
      - .:/app
volumes:
  nextjs_cache:
networks:
  diegoenriquezserrano_net:
    name: diegoenriquezserrano_network
    external: true
